### ISSUE TITLE
Link to the demo from the github page

### ISSUE THREAD

**Issue by kevmoo** [filiph/prime_finder#1]
So folks can play with it 😄

**Comment by filiph** [comment]
The big-ass "Run app here" is the link. 😃  

What would make it more clear that this is what you should click? (Serious question, I can see the current link doesn't really scream 'link'.)

**Comment by kevmoo** [comment]
But it's a header – so I scan right over it.

Change the URL next to the github description – would be more discoverable. 😄

**Comment by filiph** [comment]
Ha! Good idea. Also just pushed https://github.com/filiph/prime_finder/commit/5b06eaec1f547008d8144c3fdf380878b694d76c that hopefully makes the link in README more inviting. 

Thanks!
